baseURL = 'https://tmclo.dev/'
languageCode = 'en-us'
title = 'tmclo.dev'
summaryLength=20
theme = "shell"

author = "Tom McLoughlin"
copyright = "Copyright (c) 2022, tmclo.dev"

[params]
    name = "tmclo.dev website"
    description = "Welcome to tmclo.dev"

    github_user = "tmclo"
    github_repo = "https://github.com/tmclo/tmclo.dev"
    github_banner = false

    favicon = "favicon.ico"
    menuMore = "Show more"
    readMore = "Read more"

[build]
    writeStats = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4