name: Hugo Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup NPM/Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          ## extended: true

      - name: npm install
        run: |
            npm install
            npm install postcss-cli -g
            npm install autoprefixer -g 

      - name: Build minified
        id: build
        run: |
            hugo --minify
            echo ::set-output name=exit_code::$?

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -p 2222 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        if: steps.build.outputs.exit_code == 0
        run: rsync -avz -e 'ssh -p 2222' --rsync-path="sudo rsync" ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/tmclo/public_html
