name: Hugo Deploy

on:
    push:
      branches:
        - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NPM/Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          ## extended: true

      - name: npm install
        run: |
            npm install
            npm install postcss-cli -g
            npm install autoprefixer -g 

      - name: Build minified
        id: build
        run: |
            hugo --minify
            echo ::set-output name=exit_code::$?

      # Run a build step here if your project requires

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tmclo-dev
          directory: ./public/
          branch: main