name: Hugo Test

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true 
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          # extended: true

      - name: Build
        id: build
        run: |
             hugo
             echo ::set-output name=exit_code::$?

      - name: Merge me!
        if: steps.build.outputs.exit_code == 0
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
